[project]
name = "autoemail"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.124.0",
    "imap-tools>=1.11.0",
    "pyyaml>=6.0.3",
    "uvicorn>=0.38.0",
]
